import { useState, useEffect, useCallback } from 'react';
import { useReactFlow } from '@xyflow/react';
import { useFlowStore } from '../store/useFlowStore';

export const useExecutionDebugger = (filteredEdges) => {
  const isRecording = useFlowStore(state => state.isRecording);
  const setIsRecording = useFlowStore(state => state.setIsRecording);
  const tracePath = useFlowStore(state => state.tracePath);
  const activeStep = useFlowStore(state => state.activeStep);
  const isPlaying = useFlowStore(state => state.isPlaying);
  const setIsPlaying = useFlowStore(state => state.setIsPlaying);
  const startTrace = useFlowStore(state => state.startTrace);
  const nextStep = useFlowStore(state => state.nextStep);

  const [mediaRecorder, setMediaRecorder] = useState(null);
  const { setCenter, getNode } = useReactFlow();

  const generateExecutionPath = useCallback((startNodeId) => {
    const path = [startNodeId];
    const visited = new Set([startNodeId]);
    let queue = [startNodeId];

    while (queue.length > 0) {
      const currentId = queue.shift();
      const children = filteredEdges.filter(e => e.source === currentId).map(e => e.target);

      for (const childId of children) {
        if (!visited.has(childId)) {
          visited.add(childId);
          path.push(childId);
          queue.push(childId);
        }
      }
    }
    return path;
  }, [filteredEdges]);

  const handleNodeSelectForDebug = useCallback((nodeId) => {
    if (!isRecording) return;
    const autoGeneratedPath = generateExecutionPath(nodeId);
    startTrace(autoGeneratedPath);
  }, [isRecording, generateExecutionPath, startTrace]);

  // Aktif adım değiştikçe kamerayı o düğüme sinematik olarak odaklar
  useEffect(() => {
    if (activeStep >= 0 && activeStep < tracePath.length) {
      const activeNodeId = tracePath[activeStep];
      const activeNode = getNode(activeNodeId);
      if (activeNode) {
        setCenter(activeNode.position.x + 100, activeNode.position.y + 50, { zoom: 1.1, duration: 800 });
      }
    }
  }, [activeStep, tracePath, getNode, setCenter]);

  useEffect(() => {
    let interval;
    if (isPlaying && activeStep < tracePath.length - 1) {
      interval = setInterval(() => {
        nextStep(); 
      }, 1500); 
    } else if (activeStep >= tracePath.length - 1) {
      setIsPlaying(false);
    }
    return () => clearInterval(interval);
  }, [isPlaying, activeStep, tracePath.length, nextStep, setIsPlaying]);

  // Düğümlere (Node) anlık CSS state'lerini gönderecek fonksiyon
  const getDebugStateForNode = useCallback((nodeId) => {
    const stepIndex = tracePath.indexOf(nodeId);
    const isInTrace = stepIndex !== -1;
    return {
      isRecording,
      isInTrace,
      isTraceActive: isInTrace && stepIndex === activeStep,
      isDimmed: tracePath.length > 0 && !isInTrace,
      stepNumber: isInTrace ? stepIndex + 1 : null
    };
  }, [tracePath, activeStep, isRecording]);

  const startMp4Recording = useCallback(async () => {
    try {
      const stream = await navigator.mediaDevices.getDisplayMedia({ video: { displaySurface: "browser" }, audio: false });
      const recorder = new MediaRecorder(stream, { mimeType: 'video/webm' });
      const chunks = [];
      recorder.ondataavailable = e => chunks.push(e.data);
      recorder.onstop = () => {
        const blob = new Blob(chunks, { type: 'video/mp4' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `FlowLens_Trace_${new Date().getTime()}.mp4`;
        a.click();
      };
      recorder.start();
      setMediaRecorder(recorder);
    } catch (err) {
      console.error("Ekran kaydı başlatılamadı:", err);
    }
  }, []);

  const stopMp4Recording = useCallback(() => {
    if (mediaRecorder && mediaRecorder.state !== 'inactive') {
      mediaRecorder.stop();
      mediaRecorder.stream.getTracks().forEach(t => t.stop());
      setMediaRecorder(null);
    }
  }, [mediaRecorder]);

  return {
    handleNodeSelectForDebug,
    getDebugStateForNode,
    startMp4Recording,
    stopMp4Recording,
    isCapturingMp4: !!mediaRecorder
  };
};